server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.format_sql: true
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB  

app:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 86400000
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
logging:
  level:
    root: INFO
    org.springframework.security: INFO
